Repository AppLozic/ApplozicSwift, pull requests merged in 2019-10, with the labels that each got.

#262 [AL-3847] Rich message refractoring
  CHANGELOG.md
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__with_default_settings__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__with_different_backgroundColor__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__with_different_color__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__with_different_font__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__with_different_width__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/ALKCurvedButton__without_border__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__with_default_settings__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__with_different_backgroundColor__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__with_different_color__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__with_different_font__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__with_different_width__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKCurvedButtonSnapshotTests/CurvedImageButton__without_border__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKQuickReplyViewSnapshotTests/ALKQuickReplyView__with_large_texts__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKQuickReplyViewSnapshotTests/ALKQuickReplyView__with_small_texts__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKQuickReplyViewSnapshotTests/SuggestedReplyView__with_large_texts__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/ReferenceImages/ALKQuickReplyViewSnapshotTests/SuggestedReplyView__with_small_texts__has_a_valid_snapshot@2x.png
  Demo/ApplozicSwiftDemoTests/Tests/ALKCurvedButtonSnapshotTests.swift
  Demo/ApplozicSwiftDemoTests/Tests/ALKQuickReplyViewSnapshotTests.swift
  RichMessageKit/Models/SuggestedReplyMessage.swift
  RichMessageKit/Protocols/RichButtonView.swift
  RichMessageKit/Utilities/SuggestedReplyViewSizeCalculator.swift
  RichMessageKit/Views/ReceivedButtonsCell.swift
  RichMessageKit/Views/SentButtonsCell.swift
  RichMessageKit/Views/core/CurvedButton.swift
  RichMessageKit/Views/core/CurvedImageButton.swift
  RichMessageKit/Views/core/FAQMessageView.swift
  RichMessageKit/Views/core/SuggestedReplyView.swift
  Sources/Controllers/ALKConversationViewController+TableView.swift
  Sources/Controllers/ALKConversationViewController.swift
  Sources/Utilities/ALKMessageViewModel+Extension.swift
  Sources/Utilities/QuickReplyConfig.swift
  Sources/ViewModels/ALKConversationViewModel.swift
  Sources/Views/ALKCurvedButton.swift
  Sources/Views/ALKFriendQuickReplyCell.swift
  Sources/Views/ALKMessageButtonCell.swift
  Sources/Views/ALKMyQuickReplyCell.swift
  Sources/Views/ALKQuickReplyView.swift
  Sources/Views/ButtonsView.swift
Labels: Status: Completed, critical change, product/internal, ready for review

#264 [AL-3855] Remove empty lines before sending message #trivial
  Demo/ApplozicSwiftDemo.xcodeproj/project.pbxproj
  Demo/ApplozicSwiftDemoTests/Tests/NSAttributedStringExtensionTests.swift
  Sources/Controllers/ALKConversationViewController.swift
  Sources/Utilities/NSAttributedString+Extension.swift
Labels: Priority: High, Type: Bug, ready for review

#263 Fix issues with rich message actions #trivial
  Sources/Controllers/ALKConversationViewController.swift
  Sources/Models/CardTemplate.swift
  Sources/Utilities/Encodable+Extension.swift
  Sources/Views/ALKGenericCardCell.swift
Labels: Priority: High, Status: Completed, Type: Bug, ready for review

#258 [AL-3642]Add support for message search
  ApplozicSwift.podspec
  CHANGELOG.md
  Demo/Podfile.lock
  Sources/Controllers/ALKConversationListViewController.swift
  Sources/Controllers/ALKConversationViewController+TableView.swift
  Sources/Controllers/SearchResultViewController.swift
  Sources/Models/ALKConfiguration.swift
  Sources/Resources/ALKAssets.xcassets/Chat list/search.imageset/Contents.json
  Sources/Resources/ALKAssets.xcassets/Chat list/search.imageset/search.pdf
  Sources/ViewModels/SearchResultViewModel.swift
  Sources/Views/CustomSearchBar.swift
Labels: Status: Completed, product/new

#265 [AL-3852] Add setting for message bubble border
  CHANGELOG.md
  Sources/Controllers/ALKConversationViewController.swift
  Sources/Utilities/ALKImageView+Extension.swift
  Sources/Utilities/Message+Style.swift
  Sources/Utilities/UIView+Extension.swift
  Sources/Views/ALKFriendContactMessageCell.swift
  Sources/Views/ALKFriendMessageCell.swift
  Sources/Views/ALKFriendVoiceCell.swift
  Sources/Views/ALKMessageBaseCell.swift
  Sources/Views/ALKMyContactMessageCell.swift
  Sources/Views/ALKMyMessageCell.swift
  Sources/Views/ALKMyVoiceCell.swift
  Sources/Views/ALKPhotoCell.swift
  Sources/Views/ContactView.swift
Labels: Priority: High, Status: Completed, product/new, ready for review

#269 [AL-3854] Add support to show mute icon in list if the chat is muted
  CHANGELOG.md
  Sources/Resources/ALKAssets.xcassets/Icons/muted.imageset/Contents.json
  Sources/Resources/ALKAssets.xcassets/Icons/muted.imageset/mute.pdf
  Sources/Views/ALKChatCell.swift
  Sources/Views/ContactView.swift
Labels: Priority: High, Status: Completed, product/new, ready for review

#270 Update MGSwipeTableCell for iOS 13 and update swipe buttons after mute
  ApplozicSwift.podspec
  Demo/Podfile.lock
  Sources/Controllers/ALKConversationListTableViewController.swift
  Sources/Utilities/UITableView+Extension.swift
Labels: Priority: High, Status: Completed, product/internal, ready for review

#274 Fix push notification issue in search controller #trivial
  Sources/Controllers/ALKConversationListViewController.swift
  Sources/Controllers/ALKSearchResultViewController.swift
  Sources/Utilities/ALKPushNotificationHandler.swift
  Sources/Utilities/NotificationHelper.swift
Labels: Status: Completed, Type: Bug, ready for merge

#276 Update viewmodel with downloaded filepath #trivial
  Sources/ViewModels/ALKConversationViewModel.swift
  Sources/Views/ALKPhotoCell.swift
  Sources/Views/ALKVideoCell.swift
Labels: Type: Bug, ready for review

#277 [AL 3826]Show reply message in popup when it is not visible in the list.
  ApplozicSwift.podspec
  CHANGELOG.md
  Demo/Podfile.lock
  Sources/Controllers/ALKConversationViewController.swift
  Sources/Controllers/ALKMediaViewerViewController.swift
  Sources/Controllers/ALKReplyController.swift
  Sources/Resources/Base.lproj/Localizable.strings
  Sources/Utilities/ALKFileUtils.swift
  Sources/Utilities/ALKPushNotificationHandler.swift
  Sources/Utilities/NotificationHelper.swift
  Sources/Utilities/SystemMessage.swift
  Sources/ViewModels/ALKMediaViewerViewModel.swift
  Sources/Views/ALKAttatchmentView.swift
  Sources/Views/ALKMessageBaseCell.swift
  Sources/Views/ALKReplyMessageView.swift
  Sources/Views/ALKVideoCell.swift
Labels: product/custom, ready for review
